# Use 256 and RGB capabilities (make sure the terminal actually supports these)
set -s default-terminal "tmux-256color"
set -as terminal-features ",xterm*:RGB"
set -ga terminal-overrides ",*256col*:Tc"

# 将 Zsh 设置为 tmux 的默认 shell
set -g default-shell /bin/zsh

# 告诉 tmux 新窗口和面板都使用 Zsh
set-option -g default-command /bin/zsh



set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Enable focus events
set -s focus-events on

# Remove delay after ESC is pressed
set -s escape-time 0

# Increase scrollback
set -g history-limit 150000

# Show status line messages until key is pressed
set -g display-time 0

# Enable mouse
set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane

# vi keys in copy-mode and in status line
set -g mode-keys vi
set -g status-keys vi

set -g @open-lazygit 'g'

# tpm & plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'b0o/tmux-autoreload'
# set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'
set -g @plugin 'eglinuxer/tmux-nerd-font-window-name'
set -g @plugin 'jaclu/tmux-power-zoom'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
# set -g @plugin 'erikw/tmux-powerline'
set -g @plugin "nordtheme/tmux"
set -g @yank_action "copy-pipe"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.config/tmux/plugins/tpm/tpm'

# 自定义窗口格式 - 显示 docker 容器名称
set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W#(~/.config/tmux/scripts/window-name.sh #{pane_pid}) #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W#(~/.config/tmux/scripts/window-name.sh #{pane_pid}) #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
